# Change these first
owner: sumukha # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: AWFL
    url: https://awebsiteforlawyers.com
    maxResponseTime: 1000
  - name: SedWeb
    url: https://sedonawebsitedesign.com
  - name: SBWeb
    url: https://santabarbara-webdesign.com
  - name: Admark
    url: https://admarkimprint.com
  - name: Ami Sarasvati
    url: https://amisarasvati.com
  - name: Ami learntoplaynaf.com
    url: https://learntoplaynaf.com
  - name: Ami learntoplaynaf.com/learn/
    url: https://learntoplaynaf.com/learn/  
  - name: ASAP
    url: https://asapcats.org
  - name: ANHA
    url: https://aznaturalhistory.org
  - name: BigPark
    url: https://bigparkcouncil.org
  - name: Brent W Davis
    url: https://brentwdavis.com
  - name: GGG
    url: https://ggglawfirm.com    
  - name: Immigration Lawyer News
    url: https://immigration-lawyer-news.com
  - name: iPipoles
    url: https://ipipoles.com
  - name: Jacopo
    url: https://jacopogiacopuzzi.com
  - name: Jaimmigration
    url: https://jaimmigrationlaw.com
  - name: iPalpiti
    url: https://ipalpiti.org
  - name: sbpsychotherapy
    url: https://sbpsychotherapy.com
  - name: sfdeportationattorney
    url: https://sfdeportationattorney.com
  - name: sbnbcc
    url: https://sbnbcc.org   
  - name: Sedona-farmers-market.com
    url: https://sedona Farmers Market.com
  - name: SB Private Chef
    url: https://sb-privatechef.com
  - name: SCCSedona
    url: https://sccsedona.org
  - name: Schonfeld
    url: https://schonfeldushan.com
  - name: Visalobo
    url: https://visalobo.com    
  - name: Visawolf
    url: https://visawolf.com
  - name: Yardenlaw
    url: https://yardenlaw.com
  - name: Yevoli
    url: https://yevoliandmalayev.com   
  - name: Google
    url: https://www.google.com
  - name: Nonprofit 
    url: https://nonprofit-websitedesign.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime**."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
